name: imdb_sentiment_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - notebook
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - nltk
  - requests
  - beautifulsoup4
  - lxml
  - tqdm
  - vaderSentiment
  - wordcloud
  - xgboost
  - imbalanced-learn
