name: imdb_sentiment_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - notebook
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - nltk
  - requests
  - beautifulsoup4
  - lxml
  - tqdm
  - vaderSentiment
  - wordcloud
  - xgboost
  - imbalanced-learn
  - spaCy==3.5.0
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1.tar.gz


